name: c2w_food_factory
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.0
  sqflite: ^2.3.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - 'assets/images/Chinise-food.jpg'
    - 'assets/images/fastfood.jpg'
    - 'assets/images/foodmain.jpeg'
    - 'assets/images/South.jpeg'
    - 'assets/images/starter.jpg'
    - 'assets/images/samosa.jpg'
    - 'assets/images/indian.jpg'
    - 'assets/images/jumbo.webp'
    - 'assets/images/idli.jpg'
    - 'assets/images/food.jpg'
  uses-material-design: true
